from typing import Optional


AFFILIATE_DATABASE: dict[str, dict] = {
    "n8n": {
        "name": "n8n",
        "pricing_tier": "free_self_hosted",
        "affiliate_support": True,
        "affiliate_url": "https://n8n.io/affiliates",
        "price_advantage": "80% cheaper than Zapier",
        "category": "automation",
        "notes": "Fully open source, self-host free",
    },
    "make": {
        "name": "Make",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://www.make.com/en/affiliate-program.html",
        "price_advantage": "30% cheaper than Zapier",
        "category": "automation",
        "notes": "Formerly Integromat",
    },
    "integrately": {
        "name": "Integrately",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://www.integrately.com/affiliate",
        "price_advantage": "50% cheaper than Zapier",
        "category": "automation",
        "notes": "Simple automations at lower price",
    },
    "pabbly": {
        "name": "Pabbly",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://pabbly.com/affiliate-program/",
        "price_advantage": "70% cheaper than Zapier",
        "category": "automation",
        "notes": "Unlimited workflows on higher tiers",
    },
    "workato": {
        "name": "Workato",
        "pricing_tier": "enterprise",
        "affiliate_support": True,
        "affiliate_url": "https://www.workato.com/affiliate-program/",
        "price_advantage": "Comparable to Zapier but more enterprise features",
        "category": "automation",
        "notes": "Enterprise-focused",
    },
    "ifttt": {
        "name": "IFTTT",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://ifttt.com/affiliate",
        "price_advantage": "Free tier available",
        "category": "automation",
        "notes": "Simple consumer automations",
    },
    "pipedrive": {
        "name": "Pipedrive",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.pipedrive.com/en/affiliates",
        "price_advantage": "20% cheaper than HubSpot",
        "category": "crm",
        "notes": "CRM-focused, less bloat than HubSpot",
    },
    "activecampaign": {
        "name": "ActiveCampaign",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.activecampaign.com/affiliate-program",
        "price_advantage": "30% cheaper than HubSpot",
        "category": "crm",
        "notes": "Email marketing + CRM",
    },
    "hubspot": {
        "name": "HubSpot",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://www.hubspot.com/affiliates",
        "price_advantage": "Free CRM tier available",
        "category": "crm",
        "notes": "Free tier but expensive upgrades",
    },
    "zapier": {
        "name": "Zapier",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://zapier.com/affiliate",
        "price_advantage": "Industry standard",
        "category": "automation",
        "notes": "Most integrations, premium pricing",
    },
    "mailchimp": {
        "name": "Mailchimp",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://mailchimp.com/affiliate/",
        "price_advantage": "Free up to 500 contacts",
        "category": "crm",
        "notes": "Email marketing focus",
    },
    "sendgrid": {
        "name": "SendGrid",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://sendgrid.com/affiliate/",
        "price_advantage": "Free 100 emails/day",
        "category": "automation",
        "notes": "Transactional email specialist",
    },
    "klaviyo": {
        "name": "Klaviyo",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://www.klaviyo.com/affiliates",
        "price_advantage": "Free up to 250 contacts",
        "category": "crm",
        "notes": "E-commerce email marketing",
    },
    "convertkit": {
        "name": "ConvertKit",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://convertkit.com/affiliates",
        "price_advantage": "Free up to 300 subscribers",
        "category": "crm",
        "notes": "Creator-focused email marketing",
    },
    "trello": {
        "name": "Trello",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://trello.com/affiliates",
        "price_advantage": "Free tier very generous",
        "category": "project_management",
        "notes": "Kanban boards, Atlassian owned",
    },
    "asana": {
        "name": "Asana",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://asana.com/affiliates",
        "price_advantage": "Free for 15 users",
        "category": "project_management",
        "notes": "More features than Trello",
    },
    "clickup": {
        "name": "ClickUp",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://clickup.com/affiliate",
        "price_advantage": "Unlimited free tier",
        "category": "project_management",
        "notes": "All-in-one, very feature-rich",
    },
    "monday": {
        "name": "Monday.com",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://monday.com/affiliate-program",
        "price_advantage": "Competitive pricing",
        "category": "project_management",
        "notes": "Visual work OS",
    },
    "notion": {
        "name": "Notion",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://www.notion.so/affiliates",
        "price_advantage": "Free for personal use",
        "category": "knowledge_management",
        "notes": "Wiki + docs + project management",
    },
    "coda": {
        "name": "Coda",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://coda.io/affiliates",
        "price_advantage": "Free for 1 doc, generous team plan",
        "category": "knowledge_management",
        "notes": "Docs + tables + workflows",
    },
    "slack": {
        "name": "Slack",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://slack.com/affiliates",
        "price_advantage": "Free tier with 90-day history",
        "category": "automation",
        "notes": "Communication platform",
    },
    "discord": {
        "name": "Discord",
        "pricing_tier": "free",
        "affiliate_support": True,
        "affiliate_url": "https://discord.com/affiliates",
        "price_advantage": "Completely free",
        "category": "automation",
        "notes": "Community + communication",
    },
    "zendesk": {
        "name": "Zendesk",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.zendesk.com/affiliate/",
        "price_advantage": "Industry standard",
        "category": "customer_support",
        "notes": "Expensive for small teams",
    },
    "intercom": {
        "name": "Intercom",
        "pricing_tier": "subscription",
        "affiliate_support": True,
        "affiliate_url": "https://www.intercom.com/affiliates",
        "price_advantage": "Conversational CRM approach",
        "category": "customer_support",
        "notes": "Expensive, strong product",
    },
    "freshdesk": {
        "name": "Freshdesk",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://www.freshworks.com/affiliate/",
        "price_advantage": "30% cheaper than Zendesk",
        "category": "customer_support",
        "notes": "Freshworks ecosystem",
    },
    "helpscout": {
        "name": "HelpScout",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.helpscout.com/affiliate/",
        "price_advantage": "20% cheaper than Zendesk",
        "category": "customer_support",
        "notes": "Mailbox-focused support",
    },
    "linear": {
        "name": "Linear",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://linear.app/affiliate",
        "price_advantage": "Free for small teams",
        "category": "project_management",
        "notes": "GitHub integration, fast UI",
    },
    "github": {
        "name": "GitHub",
        "pricing_tier": "free",
        "affiliate_support": True,
        "affiliate_url": "https://github.com/affiliates",
        "price_advantage": "Free unlimited public repos",
        "category": "project_management",
        "notes": "Code collaboration standard",
    },
    "gitlab": {
        "name": "GitLab",
        "pricing_tier": "free",
        "affiliate_support": True,
        "affiliate_url": "https://about.gitlab.com/affiliates/",
        "price_advantage": "Fully free self-hosted",
        "category": "project_management",
        "notes": "Full DevOps platform free",
    },
    "bitbucket": {
        "name": "Bitbucket",
        "pricing_tier": "free",
        "affiliate_support": True,
        "affiliate_url": "https://bitbucket.org/affiliates",
        "price_advantage": "Free up to 5 users",
        "category": "project_management",
        "notes": "Atlassian ecosystem",
    },
    "airtable": {
        "name": "Airtable",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://airtable.com/affiliates",
        "price_advantage": "Free up to 1000 records",
        "category": "internal_tools",
        "notes": "Spreadsheet + database hybrid",
    },
    "baserow": {
        "name": "Baserow",
        "pricing_tier": "free_self_hosted",
        "affiliate_support": True,
        "affiliate_url": "https://baserow.io/affiliate",
        "price_advantage": "100% free self-hosted",
        "category": "internal_tools",
        "notes": "Self-hosted Airtable alternative",
    },
    "jira": {
        "name": "Jira",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.atlassian.com/affiliate",
        "price_advantage": "Free up to 10 users",
        "category": "project_management",
        "notes": "Enterprise-grade, complex",
    },
    "shortcut": {
        "name": "Shortcut",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://shortcut.com/affiliates",
        "price_advantage": "Free for 3 months",
        "category": "project_management",
        "notes": "Story-focused project management",
    },
    "basecamp": {
        "name": "Basecamp",
        "pricing_tier": "flat",
        "affiliate_support": True,
        "affiliate_url": "https://basecamp.com/affiliates",
        "price_advantage": "Flat $99/month for unlimited users",
        "category": "project_management",
        "notes": "Simple, no per-user pricing",
    },
    "wrike": {
        "name": "Wrike",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.wrike.com/affiliate/",
        "price_advantage": "Competitive enterprise pricing",
        "category": "project_management",
        "notes": "Enterprise features",
    },
    "proofhub": {
        "name": "ProofHub",
        "pricing_tier": "flat",
        "affiliate_support": True,
        "affiliate_url": "https://www.proofhub.com/affiliates",
        "price_advantage": "Flat $45/month unlimited users",
        "category": "project_management",
        "notes": "Simple flat pricing",
    },
    "zoho": {
        "name": "Zoho",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://www.zoho.com/affiliates.html",
        "price_advantage": "Free tier available, very cheap",
        "category": "crm",
        "notes": "Full suite, excellent pricing",
    },
    "freshsales": {
        "name": "Freshsales",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.freshworks.com/affiliate/",
        "price_advantage": "30% cheaper than Salesforce",
        "category": "crm",
        "notes": "Freshworks CRM",
    },
    "nutshell": {
        "name": "Nutshell",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://nutshell.com/affiliates/",
        "price_advantage": "Affordable CRM",
        "category": "crm",
        "notes": "Sales-focused CRM",
    },
    "close": {
        "name": "Close",
        "pricing_tier": "subscription",
        "affiliate_support": True,
        "affiliate_url": "https://close.com/affiliates/",
        "price_advantage": "All-in price, no per-user fee",
        "category": "crm",
        "notes": "Sales CRM for startups",
    },
    "pandadoc": {
        "name": "PandaDoc",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.pandadoc.com/affiliate-program/",
        "price_advantage": "Proposals and e-signatures",
        "category": "proposal",
        "notes": "Document automation",
    },
    "docusign": {
        "name": "DocuSign",
        "pricing_tier": "subscription",
        "affiliate_support": True,
        "affiliate_url": "https://www.docusign.com/affiliates",
        "price_advantage": "Industry standard",
        "category": "e_signature",
        "notes": "Expensive for small volume",
    },
    "hellosign": {
        "name": "HelloSign",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.hellosign.com/affiliates",
        "price_advantage": "20% cheaper than DocuSign",
        "category": "e_signature",
        "notes": "Dropbox subsidiary, now HelloSign",
    },
    "signrequest": {
        "name": "SignRequest",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://signrequest.com/affiliates",
        "price_advantage": "Free up to 5 docs/month",
        "category": "e_signature",
        "notes": "Simple e-signatures",
    },
    "confluence": {
        "name": "Confluence",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.atlassian.com/affiliate",
        "price_advantage": "Free up to 10 users",
        "category": "knowledge_management",
        "notes": "Atlassian wiki, enterprise-heavy",
    },
    "gitbook": {
        "name": "GitBook",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://www.gitbook.com/affiliates",
        "price_advantage": "Free for open source",
        "category": "knowledge_management",
        "notes": "Developer-friendly docs",
    },
    "mintlify": {
        "name": "Mintlify",
        "pricing_tier": "free",
        "affiliate_support": True,
        "affiliate_url": "https://mintlify.com/affiliates",
        "price_advantage": "Free for public docs",
        "category": "knowledge_management",
        "notes": "Beautiful doc sites",
    },
    "stripe": {
        "name": "Stripe",
        "pricing_tier": "transaction",
        "affiliate_support": True,
        "affiliate_url": "https://stripe.com/affiliates",
        "price_advantage": "Industry standard 2.9%+30c",
        "category": "automation",
        "notes": "Payments, not direct Zapier alternative",
    },
    "square": {
        "name": "Square",
        "pricing_tier": "transaction",
        "affiliate_support": True,
        "affiliate_url": "https://squareup.com/affiliates",
        "price_advantage": "Free POS basic",
        "category": "automation",
        "notes": "POS + payments",
    },
    "shopify": {
        "name": "Shopify",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.shopify.com/affiliates",
        "price_advantage": "14-day free trial",
        "category": "automation",
        "notes": "E-commerce platform",
    },
    "woocommerce": {
        "name": "WooCommerce",
        "pricing_tier": "free_plugin",
        "affiliate_support": True,
        "affiliate_url": "https://www.woocommerce.com/affiliates/",
        "price_advantage": "Free WordPress plugin",
        "category": "automation",
        "notes": "Self-hosted e-commerce",
    },
    "salesforce": {
        "name": "Salesforce",
        "pricing_tier": "enterprise",
        "affiliate_support": True,
        "affiliate_url": "https://www.salesforce.com/affiliates/",
        "price_advantage": "Enterprise standard",
        "category": "crm",
        "notes": "Most expensive CRM, massive",
    },
    "servicenow": {
        "name": "ServiceNow",
        "pricing_tier": "enterprise",
        "affiliate_support": True,
        "affiliate_url": "https://www.servicenow.com/affiliates",
        "price_advantage": "Enterprise ITSM standard",
        "category": "internal_tools",
        "notes": "Very expensive enterprise",
    },
    "quickbase": {
        "name": "QuickBase",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.quickbase.com/affiliates",
        "price_advantage": "Competitive enterprise pricing",
        "category": "internal_tools",
        "notes": "Enterprise database apps",
    },
    "smartsheet": {
        "name": "Smartsheet",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.smartsheet.com/affiliates",
        "price_advantage": "Spreadsheet-like interface",
        "category": "project_management",
        "notes": "Enterprise spreadsheet app",
    },
    "dropbox": {
        "name": "Dropbox",
        "pricing_tier": "freemium",
        "affiliate_support": True,
        "affiliate_url": "https://www.dropbox.com/affiliates",
        "price_advantage": "2GB free",
        "category": "automation",
        "notes": "File storage standard",
    },
    "googledrive": {
        "name": "Google Drive",
        "pricing_tier": "freemium",
        "affiliate_support": False,
        "affiliate_url": "",
        "price_advantage": "15GB free",
        "category": "automation",
        "notes": "Google ecosystem",
    },
    "onedrive": {
        "name": "OneDrive",
        "pricing_tier": "freemium",
        "affiliate_support": False,
        "affiliate_url": "",
        "price_advantage": "5GB free",
        "category": "automation",
        "notes": "Microsoft ecosystem",
    },
    "box": {
        "name": "Box",
        "pricing_tier": "tiered",
        "affiliate_support": True,
        "affiliate_url": "https://www.box.com/affiliates",
        "price_advantage": "Enterprise file sharing",
        "category": "automation",
        "notes": "Enterprise content management",
    },
}


def lookup_alternative(name: str) -> Optional[dict]:
    key = name.lower().strip()
    return AFFILIATE_DATABASE.get(key)


def get_all_affiliate_saas() -> list[dict]:
    return [entry for entry in AFFILIATE_DATABASE.values() if entry.get("affiliate_support", False)]


def get_db_stats() -> dict:
    total = len(AFFILIATE_DATABASE)
    with_affiliate = sum(1 for e in AFFILIATE_DATABASE.values() if e.get("affiliate_support", False))
    by_category: dict[str, int] = {}
    for entry in AFFILIATE_DATABASE.values():
        cat = entry.get("category", "unknown")
        by_category[cat] = by_category.get(cat, 0) + 1
    return {
        "total_saas": total,
        "with_affiliate": with_affiliate,
        "by_category": by_category,
    }


KNOWLEDGE_MAP: dict[str, list[str]] = {
    "zapier": ["n8n", "make", "integrately", "pabbly", "ifttt", "workato"],
    "hubspot": ["pipedrive", "activecampaign", "zoho", "freshsales", "nutshell", "close", "mailchimp"],
    "salesforce": ["pipedrive", "hubspot", "zoho", "freshsales", "nutshell", "close", "activecampaign"],
    "jira": ["linear", "asana", "clickup", "trello", "monday", "shortcut", "basecamp", "wrike", "proofhub"],
    "airtable": ["baserow", "nocoDB", "stackby", "seal"],
    "monday": ["clickup", "asana", "trello", "linear", "basecamp", "wrike", "proofhub"],
    "notion": ["coda", "confluence", "gitbook", "mintlify", "slite"],
    "zendesk": ["freshdesk", "helpscout", "intercom", "crisp"],
    "asana": ["clickup", "trello", "linear", "monday", "basecamp", "wrike", "proofhub"],
    "clickup": ["asana", "trello", "linear", "monday", "basecamp", "wrike", "proofhub"],
    "pipedrive": ["hubspot", "salesforce", "zoho", "freshsales", "nutshell", "close", "activecampaign"],
    "intercom": ["zendesk", "freshdesk", "helpscout", "crisp", "tidio"],
    "linear": ["jira", "asana", "clickup", "trello", "shortcut"],
    "confluence": ["notion", "coda", "gitbook", "mintlify", "slite"],
    "dropbox": ["box", "googledrive", "onedrive", "pcloud", "tresorit"],
    "shopify": ["woocommerce", "bigcommerce", "squarespace", "wix", "framer"],
    "canva": ["figma", "sketch", "affinity", "paletton"],
    "figma": ["sketch", "invision", "zeplin", "abstract", "framer"],
    "slack": ["discord", "teams", "mattermost", "zulip"],
    "sendgrid": ["mailgun", "postmark", "mailchimp", "ses"],
    "twilio": ["plivo", "messagebird", "textmagic", "nexmo"],
}


def get_known_alternatives_for(software: str) -> list[str]:
    key = software.lower().strip()
    return KNOWLEDGE_MAP.get(key, [])


def lookup_alternative_by_category(category: str) -> list[dict]:
    return [e for e in AFFILIATE_DATABASE.values() if e.get("category") == category and e.get("affiliate_support")]